*Check for any duplicate and if any remove them

*standardise data and fix error

Data Cleaning In Panadas

In [130]:
import pandas as pd

import dataset

In [131]:
df = pd.read_excel("Datasets/ccl.xlsx")

In [132]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [133]:
type(df)

pandas.core.frame.DataFrame

In [134]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
dtype: bool

In [135]:
df.iloc[20]

CustomerID                                  1020
First_Name                                Anakin
Last_Name                              Skywalker
Phone_Number                        876|678|3469
Address              910 Tatooine Road, Tatooine
Paying Customer                              Yes
Do_Not_Contact                                 N
Not_Useful_Column                           True
Name: 20, dtype: object

In [136]:
df.tail(5)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [137]:
fd

<bound method DataFrame.duplicated of    CustomerID First_Name    Last_Name Phone_Number Paying Customer  \
0        1002       Abed        Nadir   1236439775               N
1        1003     Walter       /White   7066950392               N
2        1008   Sherlock       Holmes   8766783469               N
3        1015       Toby  Flenderson_   3047622467               N
4        1016        Ron      Weasley   1235455421               N

  Do_Not_Contact        Street_Address City Pin_code
0              N   93 West Main Street
1              N    298 Drugs Driveway
2              N         98 Clue Drive
3              N         214 HR Avenue
4              N  2395 Hogwarts Avenue                >

In [138]:
fd = df.duplicated

In [139]:
df.duplicated().sum()

np.int64(1)

In [140]:
df[fd]

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [141]:
df.drop_duplicates(inplace=True)

In [142]:
df.duplicated().sum

<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool>

In [143]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

Step2

In [144]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

In [145]:
df['Last_Name']

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [146]:
ln ="...Poter"
ln.strip()

'...Poter'

In [147]:
df['Last_Name'].str.strip()

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [148]:
df['Last_Name'].str.strip("123._/")

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

In [149]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

STEP TO MAKE ALL NUMBER IN THE PHONENUMBER COLUMN TO BE OF SAME LENGTH AND format
STEP1 - REPLACE ALL THE UNWANTED CHACTERS TO EMPTY STRING(")")

#python string

In [150]:
name = "mike-tyson" 
name=name.replace("_","")

In [151]:
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [152]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [153]:
df['Phone_Number'].str.replace("[^0-9]","",regex=True)

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18
19    8766783469
Name: Phone_Number, dtype: object

In [154]:
df['Phone_Number'].str.replace("[^0-9]","",regex=True)

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18
19    8766783469
Name: Phone_Number, dtype: object

In [155]:
l1 = lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]
l1("1234567890")

'123-456-7890'

### apply ()=>Apply is a pandas function which will apply specified funcationality to each value of series

In [156]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x : str(x))

In [157]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              nan
7     876|678|3469
8              N/a
9     123-545-5421
10             nan
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [158]:
df['Phone_Number']=df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [159]:
df['Phone_Number']

0     1235455421
1     1236439775
2     7066950392
3     1235432345
4     8766783469
5     3047622467
6
7     8766783469
8
9     1235455421
10
11    7066950392
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17    7066950392
18
19    8766783469
Name: Phone_Number, dtype: object

In [160]:
# i want to appdf['Ply the above lambda functoin to all the values in the phone number column
type(df['Phone_Number'][17])

str

In [161]:
df['Phone_Number']=df['Phone_Number'].apply(l1)

In [162]:
l1 = lambda x:x[0:3]+"-"+x[3:6]+"-"+x[6:10]

In [163]:
df['Phone_Number']=df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [164]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x : str(x))

In [165]:
df['Phone_Number']=df['Phone_Number'].str.replace("[^0-9]","",regex=True)

In [166]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [167]:
## address
df['Address']

0                     123 Shire Lane, Shire
1                       93 West Main Street
2                        298 Drugs Driveway
3     980 Paper Avenue, Pennsylvania, 18503
4                          123 Dragons Road
5                          768 City Parkway
6                         1209 South Street
7                             98 Clue Drive
8                          123 Middle Earth
9                25th Main Street, New York
10                    612 Shire Lane, Shire
11                     2394 Hogwarts Avenue
12                         2039 Main Street
13                         343 City Parkway
14                            214 HR Avenue
15                     2395 Hogwarts Avenue
16           121 Paper Avenue, Pennsylvania
17                          3498 Super Lane
18                                      N/a
19              910 Tatooine Road, Tatooine
Name: Address, dtype: object

In [168]:
## address
df['Address'].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [169]:
fullname ="Virat, Kholi"
fullname.split(',')

['Virat', ' Kholi']

In [170]:
#spliting address into 3 step cols
df[['Street_Address','City','Pin_code']]=df['Address'].str.split(',',expand=True)

In [171]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,City,Pin_code
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,3047622467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [172]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')

In [173]:
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')

In [174]:
df['Paying Customer']

0       Y
1       N
2       N
3       Y
4       Y
5       Y
6       N
7       N
8       Y
9       Y
10      Y
11      Y
12      Y
13      Y
14      N
15      N
16      Y
17      Y
18    N/a
19      Y
Name: Paying Customer, dtype: object

In [175]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column',
       'Street_Address', 'City', 'Pin_code'],
      dtype='object')

In [176]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')

In [177]:
df['Do_Not_Contact']

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [178]:
# remove columns
df.drop(columns=['Not_Useful_Column','Address'],inplace=True)

#### Dealing with  null values

In [179]:
df.replace('N/a','',inplace=True)
df.replace('NaN','',inplace=True)

In [180]:
df.replace('--','',inplace=True)

In [181]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,7066950392,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,3047622467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,,None,None
19,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,None

In [182]:
df.fillna('A')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,A
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,A,A
2,1003,Walter,/White,7066950392,N,A,298 Drugs Driveway,A,A
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,A,A
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,A,A
6,1007,Jeff,Winger,,N,N,1209 South Street,A,A
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,A,A
8,1009,Gandalf,A,,Y,A,123 Middle Earth,A,A
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,A
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,A
11,1012,Harry,...Potter,7066950392,Y,A,2394 Hogwarts Avenue,A,A
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,A,A
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,A,A
14,1015,Toby,Flenderson_,3047622467,N,N,214 HR Avenue,A,A
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,A,A
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,A
17,1018,Clark,Kent,7066950392,Y,A,3498 Super Lane,A,A
18,1019,Creed,Braton,,,Y,,A,A
19,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,A

In [183]:
df.fillna('',inplace=True)

In [184]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,1236439775,N,Y,93 West Main Street,,
2,1003,Walter,/White,7066950392,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,1235432345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,3047622467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,7066950392,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,1235432345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,3047622467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,

In [185]:
for i in df.index:
    if df.loc[i,'Do_Not_Contact'] =="Y" or df.loc[i,'Phone_Number'] =="":
        df.drop(i,inplace=True)

In [186]:
df.reset_index(inplace=True,drop=True)

In [187]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,City,Pin_code
0,1001,Frodo,Baggins,1235455421,Y,N,123 Shire Lane,Shire,
1,1003,Walter,/White,7066950392,N,,298 Drugs Driveway,,
2,1005,Jon,Snow,8766783469,Y,N,123 Dragons Road,,
3,1008,Sherlock,Holmes,8766783469,N,N,98 Clue Drive,,
4,1010,Peter,Parker,1235455421,Y,N,25th Main Street,New York,
5,1012,Harry,...Potter,7066950392,Y,,2394 Hogwarts Avenue,,
6,1013,Don,Draper,1235432345,Y,N,2039 Main Street,,
7,1014,Leslie,Knope,8766783469,Y,N,343 City Parkway,,
8,1015,Toby,Flenderson_,3047622467,N,N,214 HR Avenue,,
9,1016,Ron,Weasley,1235455421,N,N,2395 Hogwarts Avenue,,
10,1017,Michael,Scott,1236439775,Y,N,121 Paper Avenue,Pennsylvania,
11,1018,Clark,Kent,7066950392,Y,,3498 Super Lane,,
12,1020,Anakin,Skywalker,8766783469,Y,N,910 Tatooine Road,Tatooine,